spring.application.name=Student_Management_System


# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/student_management
spring.datasource.username=root
spring.datasource.password=mahendra

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# JWT
# ===============================
jwt.secret=ZmY3YjE4NzY2M2MzYjJhOTM3ZmM4NGFhYjQxYjNkYzA3ZGEzMjg4ZjY2ZDY2MzM0ZmJkMjNmMjM2ODc4YmM0ZA==
jwt.expiration=86400000

# ===============================
# SWAGGER
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html